import path from 'path';

// File system paths for server-side code (Server Components, API routes, etc.)
// Use process.cwd() as the base - works in both dev and standalone production mode
// In dev: cwd is /client
// In Docker standalone: cwd is /app/client (we run `node server.js` from there)
export const ROOT_DIR: string = process.cwd();
export const ROOT_DIR_SRC: string = path.join(ROOT_DIR, 'src');
export const ROOT_DIR_APP: string = path.join(ROOT_DIR_SRC, 'app');

// Recursive long-form content (courses). Source is hand-edited; the dist tree is
// generated by build-content.R and is what the site reads/serves. The dist tree
// is committed (so no R toolchain is needed at build time) but fully disposable:
// delete it and rebuild from source with no loss, because every hand-edited file
// (titles, summaries, index pages) lives in ROOT_DIR_CONTENT, not the output.
export const ROOT_DIR_CONTENT: string = path.join(ROOT_DIR, 'content');
export const ROOT_DIR_CONTENT_DIST: string = path.join(
  ROOT_DIR,
  'content-dist'
);
