#!/bin/sh

initially_staged_files=$(git diff --cached --name-only --diff-filter=ACM | tr '\n' ' ')

bun run format

if [ -n "$initially_staged_files" ]; then
    echo "$initially_staged_files" | xargs git add
else
    echo "No files were initially staged."
fi

echo "pre-commit hook complete."
