---
letter: 't'
word: 'taylor-series'
dictionary: 'mathematics'
category: 'analysis'
dataSource: 'assistant'
published: true
comments: true

linksTo: ['derivative','limit','series']
linkedFrom: []
output:
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
if (knitr::is_html_output()) {
  knitr::knit_hooks$set(
    plot = function(x, options) {
      cap  <- options$fig.cap
      as.character(
        htmltools::tag("Figure",
          list(src = x, alt = cap, paste("\n\t", cap, "\n", sep=""))
        )
      )
    }
  )
}
knitr::opts_knit$set(root.dir = "/Users/work/Coding/derecksprojects/derecksnotes.com-playground/derecksnotes.com/client/src/app/dictionaries/mathematics/definitions")
knitr::knit_hooks$set(optipng = knitr::hook_optipng)
knitr::opts_chunk$set(dpi=300, fig.width=10, fig.height=7)
```

<a id="taylor-series">Taylor Series</a> - In **analysis**, the **Taylor series** of a function $f$ at a point $a$ is the infinite [series](#series):

'57989'
f(a + x) = \sum_{n=0}^{\infty} \frac{f^{(n)}(a)}{n!} x^n,
'57989'

where \(f^{(n)}(a)\) is the \(n\)th [derivative](#derivative) of \(f\) at \(a\). Convergence depends on the function and distance from \(a\).

**Key points**:
- Special case: Maclaurin series when \(a=0\).
- Approximates functions near \(a\).

**R demonstration** (partial sums for \(e^x\)):

```{r}
library(data.table)

taylor_exp <- function(x, N=10) {
  # sum_{n=0 to N} x^n / n!
  sum( sapply(0:N, function(n) x^n / factorial(n)) )
}

x_val <- 1
approx_exp <- taylor_exp(x_val, 10)
actual_exp <- exp(x_val)

c(approx_exp, actual_exp)
```
