---
letter: '#'
word: 'radical'
dictionary: 'mathematics'
category: 'arithmetic'
dataSource: 'assistant'
published: true
comments: true

linksTo: ['square-root']
linkedFrom: []
output:
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
if (knitr::is_html_output()) {
  knitr::knit_hooks$set(
    plot = function(x, options) {
      cap <- options$fig.cap
      as.character(
        htmltools::tag(
          "Figure", list(src = x, alt = cap, paste("\n\t", cap, "\n", sep=""))
        )
      )
    }
  )
}
knitr::opts_knit$set(root.dir = "/Users/work/Coding/derecksprojects/derecksnotes.com-playground/derecksnotes.com/client/src/app/dictionaries/mathematics/definitions")
knitr::knit_hooks$set(optipng = knitr::hook_optipng)
knitr::opts_chunk$set(dpi=300, fig.width=10, fig.height=7)
```

<a id="radical">√ (Radical)</a> - The **radical** symbol √ indicates the principal square root of a number. More generally, radical notation can include indices for nth roots:

'59102'
\sqrt{x}, \quad \sqrt[n]{x}.
'59102'

**Key points**:
- For nonnegative x, √x is the nonnegative root.
- In advanced contexts, negative radicands lead to complex numbers.

**R demonstration** (square root in R):

```{r}
library(data.table)

sqrt(16)  # returns 4
sqrt(-1)  # NaN in real arithmetic
```
