---
letter: 'p'
word: 'permutation'
dictionary: 'mathematics'
category: 'combinatorics'
dataSource: 'assistant'
published: true
comments: true

linksTo: ['combination']
linkedFrom: []
output:
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
if (knitr::is_html_output()) {
  knitr::knit_hooks$set(
    plot = function(x, options) {
      cap <- options$fig.cap
      as.character(
        htmltools::tag("Figure",
          list(src = x, alt = cap, paste("\n\t", cap, "\n", sep=""))
        )
      )
    }
  )
}
knitr::opts_knit$set(root.dir = "/Users/work/Coding/derecksprojects/derecksnotes.com-playground/derecksnotes.com/client/src/app/dictionaries/mathematics/definitions")
knitr::knit_hooks$set(optipng = knitr::hook_optipng)
knitr::opts_chunk$set(dpi=300, fig.width=10, fig.height=7)
```

<a id="permutation">Permutation</a> - In **combinatorics**, a **permutation** is an arrangement of all or part of a set of objects in a specific order. For $n$ distinct elements, the number of ways to arrange all of them is $n!$. When selecting $k$ from $n$ in an ordered manner:

$$
P(n, k) = \frac{n!}{(n-k)!}.
$$

Compare with a [combination](#combination), where order does not matter.

**R demonstration** (simple function for permutation count):

```{r}
library(data.table)

perm_func <- function(n,k) factorial(n)/factorial(n-k)

perm_5_3 <- perm_func(5,3)
perm_5_3
# which is 5!/2! = 60
```
