---
letter: 'm'
word: 'mean'
dictionary: 'mathematics'
category: 'statistics'
dataSource: 'assistant'
published: true
comments: true

# We might reference "distribution" or other means.
linksTo: ['harmonic-mean','distribution']
linkedFrom: []

output:
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
if (knitr::is_html_output()) {
  knitr::knit_hooks$set(
    plot = function(x, options) {
      cap <- options$fig.cap
      as.character(
        htmltools::tag(
          "Figure",
          list(src = x, alt = cap, paste("\n\t", cap, "\n", sep=""))
        )
      )
    }
  )
}
knitr::opts_knit$set(root.dir = "/Users/work/Coding/derecksprojects/derecksnotes.com-playground/derecksnotes.com/client/src/app/dictionaries/mathematics/definitions")
knitr::knit_hooks$set(optipng = knitr::hook_optipng)
knitr::opts_chunk$set(dpi=300, fig.width=10, fig.height=7)
```

<a id="mean">Mean</a> - In **statistics**, the **mean** (or average) of a set of values $x_1, x_2, \dots, x_n$ is:

$$
\bar{x} = \frac{1}{n}\sum_{i=1}^{n} x_i.
$$

This is the **arithmetic mean**. Compare to the [harmonic-mean](#harmonic-mean) or geometric mean for other contexts. The mean is often used to summarise a [distribution](#distribution).

**R demonstration**:

```{r}
library(data.table)

dt_values <- data.table(val = c(2,3,5,7,11))
mean_val <- mean(dt_values$val)
mean_val
```
