---
letter: 'n'
word: 'nested-radical'
dictionary: 'mathematics'
category: 'algebra'
dataSource: 'assistant'
published: true
comments: true
linksTo: []
linkedFrom: []
output:
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
if (knitr::is_html_output()) {
  knitr::knit_hooks$set(
    plot = function(x, options) {
      cap <- options$fig.cap
      as.character(
        htmltools::tag("Figure", list(src = x, alt = cap, paste("\n\t", cap, "\n", sep="")))
      )
    }
  )
}
knitr::opts_knit$set(root.dir = "/Users/work/Coding/derecksprojects/derecksnotes.com-playground/derecksnotes.com/client/src/app/dictionaries/mathematics/definitions")
knitr::knit_hooks$set(optipng = knitr::hook_optipng)
knitr::opts_chunk$set(dpi=300, fig.width=10, fig.height=7)
```

<a id="nested-radical">Nested Radical</a> - A **nested radical** is an expression containing radicals (square roots, etc.) inside other radicals, for example:

'56956'
\sqrt{a + \sqrt{b + \sqrt{c + \dots}}}
'56956'

Such expressions sometimes simplify to closed-forms. A famous example is:

'56956'
\sqrt{1 + 2\sqrt{1 + 3\sqrt{1 + 4\sqrt{1+ \dots}}}}
'56956'

Though symbolic manipulation is more typical than numeric for these. Minimal R demonstration here:

```{r}
# We could approximate a short nested radical numerically:
nested_radical_approx <- function(n) {
  # approximate: sqrt(1 + 2*sqrt(1 + 3*sqrt(1+...  up to n steps
  # This is more a demonstration than a standard function
  val <- 0
  for(k in seq(n, 2, by=-1)) {
    val <- sqrt(1 + k*val)
  }
  sqrt(1 + 2*val) # final
}

nested_radical_approx(5)
```
