---
letter: 'm'
word: 'mode'
dictionary: 'mathematics'
category: 'statistics'
dataSource: 'assistant'
published: true
comments: true

# We reference "distribution" again.
linksTo: ['distribution']
linkedFrom: []

output:
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
if (knitr::is_html_output()) {
  knitr::knit_hooks$set(
    plot = function(x, options) {
      cap <- options$fig.cap
      as.character(
        htmltools::tag(
          "Figure",
          list(src = x, alt = cap, paste("\n\t", cap, "\n", sep=""))
        )
      )
    }
  )
}
knitr::opts_knit$set(root.dir = "/Users/work/Coding/derecksprojects/derecksnotes.com-playground/derecksnotes.com/client/src/app/dictionaries/mathematics/definitions")
knitr::knit_hooks$set(optipng = knitr::hook_optipng)
knitr::opts_chunk$set(dpi=300, fig.width=10, fig.height=7)
```

<a id="mode">Mode</a> - In **statistics**, the **mode** is the most frequently occurring value in a [distribution](#distribution). Some distributions (e.g., uniform) may have multiple modes (or no strong mode) if all values are equally likely.

**R demonstration** (custom function):

```{r}
library(data.table)

mode_fn <- function(x) {
  # returns the value(s) with highest frequency
  tab <- table(x)
  freq_max <- max(tab)
  as.numeric(names(tab)[tab == freq_max])
}

dt_data <- data.table(vals = c(1,2,2,3,2,5,5,5))
mode_fn(dt_data$vals)
```
