---
letter: 'q'
word: 'quadratic'
dictionary: 'mathematics'
category: 'algebra'
dataSource: 'assistant'
published: true
comments: true

linksTo: ['derivative','arithmetic']
linkedFrom: []
output:
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
if (knitr::is_html_output()) {
  knitr::knit_hooks$set(
    plot = function(x, options) {
      cap  <- options$fig.cap
      as.character(
        htmltools::tag("Figure", list(src = x, alt = cap, paste("\n\t", cap, "\n", sep="")))
      )
    }
  )
}
knitr::opts_knit$set(root.dir = "/Users/work/Coding/derecksprojects/derecksnotes.com-playground/derecksnotes.com/client/src/app/dictionaries/mathematics/definitions")
knitr::knit_hooks$set(optipng = knitr::hook_optipng)
knitr::opts_chunk$set(dpi=300, fig.width=10, fig.height=7)
```

<a id="quadratic">Quadratic</a> - A **quadratic** function is a polynomial of degree 2, often written as:

'57581'
f(x) = ax^2 + bx + c,
'57581'

with $a \neq 0$. The graph is a parabola. The [derivative](#derivative) reveals a linear slope; [arithmetic](#arithmetic) underlies basic manipulations. 

**R demonstration**:

```{r}
library(data.table)
x_vals <- seq(-5,5, by=0.5)
f_quad <- function(x) 2*x^2 + 3*x - 1

dt_quad <- data.table(
  x = x_vals,
  y = f_quad(x_vals)
)
head(dt_quad)
```
