---
letter: 'x'
word: 'xnor'
dictionary: 'mathematics'
category: 'logic'
dataSource: 'assistant'
published: true
comments: true

linksTo: ['xor']
linkedFrom: []
output:
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
if (knitr::is_html_output()) {
  knitr::knit_hooks$set(
    plot = function(x, options) {
      cap <- options$fig.cap
      as.character(
        htmltools::tag("Figure", 
          list(src = x, alt = cap, paste("\n\t", cap, "\n", sep=""))
        )
      )
    }
  )
}
knitr::opts_knit$set(root.dir = "/Users/work/Coding/derecksprojects/derecksnotes.com-playground/derecksnotes.com/client/src/app/dictionaries/mathematics/definitions")
knitr::knit_hooks$set(optipng = knitr::hook_optipng)
knitr::opts_chunk$set(dpi=300, fig.width=10, fig.height=7)
```

<a id="xnor">XNOR</a> - In **logic**, **XNOR** (exclusive-NOR) is the complement of [xor](#xor). It returns true if both inputs are the same (both true or both false), and false otherwise:

$$
A \odot B = \neg (A \oplus B).
$$

**Truth table**:

| A     | B     | A XNOR B |
|-------|-------|----------|
| FALSE | FALSE | TRUE     |
| FALSE | TRUE  | FALSE    |
| TRUE  | FALSE | FALSE    |
| TRUE  | TRUE  | TRUE     |

**R demonstration** (custom xnor function on vectors):

```{r}
library(data.table)

xnor_fn <- function(a, b) {
  # complement of xor
  !( (a | b) & !(a & b) )
}

x <- c(TRUE,TRUE,FALSE,FALSE)
y <- c(TRUE,FALSE,TRUE,FALSE)
xnor_fn(x,y)
```
