---
letter: '#'
word: 'summation'
dictionary: 'mathematics'
category: 'analysis'
dataSource: 'assistant'
published: true
comments: true

linksTo: ['series','sigma-notation']
linkedFrom: []
output:
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
if (knitr::is_html_output()) {
  knitr::knit_hooks$set(
    plot = function(x, options) {
      cap <- options$fig.cap
      as.character(
        htmltools::tag("Figure", list(src = x, alt = cap, paste("\n\t", cap, "\n", sep="")))
      )
    }
  )
}
knitr::opts_knit$set(root.dir = "/Users/work/Coding/derecksprojects/derecksnotes.com-playground/derecksnotes.com/client/src/app/dictionaries/mathematics/definitions")
knitr::knit_hooks$set(optipng = knitr::hook_optipng)
knitr::opts_chunk$set(dpi=300, fig.width=10, fig.height=7)
```

<a id="summation">∑ (Summation)</a> - The **summation** symbol ∑ denotes adding a sequence of terms. For instance:

'59102'
\sum_{k=1}^{n} a_k = a_1 + a_2 + \dots + a_n.
'59102'

**Key points**:
- See also [series](#series) for infinite sums.
- Sometimes called [sigma-notation](#sigma-notation).

**R demonstration** (summing up a vector):

```{r}
library(data.table)

vals <- c(1,2,3,4,5)
sum_vals <- sum(vals)
sum_vals
```
