---
letter: 't'
word: 'tangent'
dictionary: 'mathematics'
category: 'trigonometry'
dataSource: 'assistant'
published: true
comments: true

linksTo: ['sine','angle','derivative']
linkedFrom: []
output:
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
if (knitr::is_html_output()) {
  knitr::knit_hooks$set(
    plot = function(x, options) {
      cap  <- options$fig.cap
      as.character(
        htmltools::tag("Figure",
          list(src = x, alt = cap, paste("\n\t", cap, "\n", sep=""))
        )
      )
    }
  )
}
knitr::opts_knit$set(root.dir = "/Users/work/Coding/derecksprojects/derecksnotes.com-playground/derecksnotes.com/client/src/app/dictionaries/mathematics/definitions")
knitr::knit_hooks$set(optipng = knitr::hook_optipng)
knitr::opts_chunk$set(dpi=300, fig.width=10, fig.height=7)
```

<a id="tangent">Tangent</a> - In **trigonometry**, the **tangent** of an [angle](#angle) $\theta$ is 
'57989'
\tan(\theta) = \frac{\sin(\theta)}{\cos(\theta)}.
'57989'

**Key points**:
- Tangent is periodic with period $\pi$.
- It relates to the slope of the line that touches a curve at a point (the [derivative](#derivative) concept).

**R demonstration** (basic tangent plot):

```{r}
library(data.table)
library(ggplot2)

theta_seq <- seq(-pi/2+0.1, pi/2-0.1, length.out=200)
dt_tan <- data.table(
  theta = theta_seq,
  tan_val = tan(theta_seq)
)

ggplot(dt_tan, aes(x=theta, y=tan_val)) +
  geom_line(color="blue") +
  labs(
    title="Tangent Function",
    x="theta",
    y="tan(theta)"
  ) +
  theme_minimal()
```
