---
letter: 'x'
word: 'x-intercept'
dictionary: 'mathematics'
category: 'geometry'
dataSource: 'assistant'
published: true
comments: true

linksTo: ['x-axis','polynomial']
linkedFrom: []
output:
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
if (knitr::is_html_output()) {
  knitr::knit_hooks$set(
    plot = function(x, options) {
      cap <- options$fig.cap
      as.character(
        htmltools::tag("Figure",
          list(src = x, alt = cap, paste("\n\t", cap, "\n", sep=""))
        )
      )
    }
  )
}
knitr::opts_knit$set(root.dir = "/Users/work/Coding/derecksprojects/derecksnotes.com-playground/derecksnotes.com/client/src/app/dictionaries/mathematics/definitions")
knitr::knit_hooks$set(optipng = knitr::hook_optipng)
knitr::opts_chunk$set(dpi=300, fig.width=10, fig.height=7)
```

<a id="x-intercept">X-intercept</a> - In **geometry**, the **x-intercept** of a curve is the point(s) where it crosses the [x-axis](#x-axis). Formally, points with y=0:

$$
\text{Find } x \text{ such that } f(x)=0.
$$

**Key points**:
- Solving $f(x)=0$ often involves [polynomial](#polynomial) roots or other equation solutions.
- Graphically, x-intercepts appear where the plot crosses the horizontal axis.

**R demonstration** (finding approximate x-intercept for a function):

```{r}
library(data.table)

f <- function(x) x^2 - 4
uniroot_res <- uniroot(f, c(0,5))
uniroot_res  # should be 2
```
