import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'DN',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const header = (
        <header>
            <nav>
                <Link href="/">
                    Home
                </Link>
            </nav>
        </header>
    )
    return (
        <html lang="en">
            <body className={inter.className}>
                {header}
                {children}
            </body>
        </html>
    )
}
