#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run format # prettier

# Stage the changes made by Prettier
git add -A

# npm test
# cd server
# npm run test
# cd ..

git push
echo "pre-commit hook complete."
