name: Deploy Dev to Linode

on:
  push:
    branches-ignore:
      - 'master'
  pull_request:
jobs:
  deploy_to_linode:
    name: Deploy to Linode
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set branch name as env var
        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Print branch name
        run: echo "The branch name is $BRANCH_NAME"

      - name: Execute remote build command
        uses: appleboy/ssh-action@v1.0.3
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
          envs: BRANCH_NAME
          script: |
            echo "Building branch: $BRANCH_NAME"
            eval $(ssh-agent -s)
            ssh-add ~/.ssh/github
            source /home/dereck/.nvm/nvm.sh
            nvm use v20.9.0
            cd /html/derecksnotes-playground/test-derecksnotes.com/
            git fetch
            git checkout $BRANCH_NAME
            git pull
            npm install
            cd client && npm install && npm run build && cd ..
            cd server && npm install && tsc && cd ..
            echo "${{ secrets.REMOTE_PASSWORD }}" | sudo -S systemctl restart test-derecksnotes-server
